import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const carData: Prisma.CarCreateInput[] = [
  {
    title: "Nissan Versa Advance",
    images: [
      "henry-ajquejay/ticlgy3b3dzfjxnaz6we",
      "henry-ajquejay/ufc8muleowmamdcimuxj",
      "henry-ajquejay/q3jmbsjrrdaullocymxd",
      "henry-ajquejay/ycrynvjlg0p3nfiezwd3",
      "henry-ajquejay/spphiebivjkxdb0rvkoy",
    ],
    modelYear: 2020,
    modelMake: "Nissan",
    price: 60000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.6,
    published: true,
  },
  {
    title: "Ford F150 XLT Cabina Sencilla",
    images: [
      "henry-ajquejay/jnue21p5orr6khnumzjb",
      "henry-ajquejay/d91z67naj3l5cpgerau8",
      "henry-ajquejay/szrou6335hxskxdcxhav",
      "henry-ajquejay/xwoic8gg9u2du08wksle",
      "henry-ajquejay/fwsyaw56vgmnifzsiqdg",
    ],
    modelYear: 2019,
    modelMake: "Ford",
    price: 125000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 3.5,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Volkswagen Nivus Highline",
    images: [
      "henry-ajquejay/fwsyaw56vgmnifzsiqdg",
      "henry-ajquejay/yopti3al8sndspthby3d",
      "henry-ajquejay/ayucn9zdhje3vs22typf",
      "henry-ajquejay/kvjsw9aaaggqcwjxsy2f",
      "henry-ajquejay/i6aklya6vbc89nvhtz5m",
    ],
    modelYear: 2021,
    modelMake: "Volkswagen",
    price: 110000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 20000,
    engineType: "DIESEL",
    engineCapacity: 1.0,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Renault Kwid Intense",
    images: [
      "henry-ajquejay/kutoovgjggriazzqdch5",
      "henry-ajquejay/qitso131tudepq3x3b0q",
      "henry-ajquejay/adfhyxylwekgzs6qiuc3",
      "henry-ajquejay/yujw0kkph0jrq5hzhvvc",
      "henry-ajquejay/rfmpspcxpggpephmspa7",
    ],
    modelYear: 2023,
    modelMake: "Renault",
    price: 80000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.0,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Renault Stepway Intense",
    images: [
      "henry-ajquejay/gix7gqbn0x1xhabusefz",
      "henry-ajquejay/wtes3hffoijhiejymwl9",
      "henry-ajquejay/dfvgieizizwifjhoaesf",
      "henry-ajquejay/rishsex2klhq0mzddppt",
      "henry-ajquejay/jhktxsl8tt94uxxwxegi",
    ],
    modelYear: 2020,
    modelMake: "Renault",
    price: 90000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 30000,
    engineType: "PETROL",
    engineCapacity: 1.6,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Kia Picanto X-Line 1.25 MT",
    images: [
      "henry-ajquejay/hphzfs1yqfolj16nh8hv",
      "henry-ajquejay/sjpcaqr3b6vnccdrc1jo",
      "henry-ajquejay/tejtex4go0tho1sgvc0n",
      "henry-ajquejay/frhldpfg04r35be1pgdz",
      "henry-ajquejay/rpgc1quu1nww3pbuqcvk",
    ],
    modelYear: 2023,
    modelMake: "Kia",
    price: 75000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.25,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "GMC Acadia SLE",
    images: [
      "henry-ajquejay/iy2db4lmf7hdrn5av0oj",
      "henry-ajquejay/nq2jmxm8uzxsimjlfvw2",
      "henry-ajquejay/vmq2wetqe7aenk1qni9b",
      "henry-ajquejay/slruclthqsxtqh7s2eab",
      "henry-ajquejay/o0wupeal3fpv9b5n9r4m",
      "henry-ajquejay/figcsmkr5m4lqokcfizj",
      "henry-ajquejay/x8ft177cjt1uafzpss6d",
    ],
    modelYear: 2019,
    modelMake: "GMC",
    price: 130000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 3.6,
    published: true,
  },
  {
    title: "Chevrolet Traverse LT Sport Utility 4D",
    images: [
      "henry-ajquejay/izzo4qb1o43bmri2amrz",
      "henry-ajquejay/z5sib4oud3zldkdypscb",
      "henry-ajquejay/ci5zs23izwqtpbpewxgp",
      "henry-ajquejay/qdb63xsb1mhzoftvt18c",
      "henry-ajquejay/ivfev2aghnga4rfxxami",
      "henry-ajquejay/epgirfemysloo1tbfi5v",
      "henry-ajquejay/ryqmrrz2kfm0drglqz3f",
      "henry-ajquejay/gi2lpmdv42n4cvwbpabp",
    ],
    modelYear: 2017,
    modelMake: "Chevrolet",
    price: 120000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 70000,
    engineType: "PETROL",
    engineCapacity: 3.6,
    published: true,
  },
  {
    title: "Chevrolet Trax LS Sport Utility 4D",
    images: [
      "henry-ajquejay/okiykp0v55d604nznz5x",
      "henry-ajquejay/d1czovnwzzbk8srm3pum",
      "henry-ajquejay/g465zg1caphpqwffs9ec",
      "henry-ajquejay/h8tghgjjdbfsjb4h4ojf",
      "henry-ajquejay/zgg4fycjnkvhbpwadhdo",
      "henry-ajquejay/jqxbmgnag2uhm5a4cdqe",
      "henry-ajquejay/gg34ivpuzidreg1cm2ym",
    ],
    modelYear: 2018,
    modelMake: "Chevrolet",
    price: 85000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 1.4,
    published: true,
  },
  {
    title: "Chevrolet Jeep Cherokee Trailhawk L Plus 4X4",
    images: [
      "henry-ajquejay/ziak91llffes3npkgsbt",
      "henry-ajquejay/edvqserpreuirgcpkkhf",
      "henry-ajquejay/eg7oqvfurqyxusiaypxn",
      "henry-ajquejay/yiuaq3cef9pqdy6yipd4",
      "henry-ajquejay/vcamiylghoxqcks04gib",
      "henry-ajquejay/dunlgcbmyvcozsofriop",
      "henry-ajquejay/l1jlbvr3rdf5mirrrec8",
      "henry-ajquejay/vq1wan8iow1ymm4kwq2a",
      "henry-ajquejay/u2sfoybvynz2hbjsgktx",
      "henry-ajquejay/yhtbytvjqbgfju40wyan",
    ],
    modelYear: 2018,
    modelMake: "Jeep",
    price: 110000,
    condition: "USED",
    transmission: "MANUAL",
    mileage: 50000,
    engineType: "DIESEL",
    engineCapacity: 2.0,
    published: true,
  },
  {
    title: "Nissan Altima 2.5 SV",
    images: [
      "henry-ajquejay/ytgzjbjkmviat2epwwlm",
      "henry-ajquejay/puhfwy4zqliujfnzowbx",
      "henry-ajquejay/qnw8ezdidx9r3pk88sau",
      "henry-ajquejay/wjibz4x5rv6gzxmsrcsg",
      "henry-ajquejay/p2negkxyxs1hotx3aujb",
      "henry-ajquejay/kw9eyr2jr5om0eczom9k",
    ],
    modelYear: 2018,
    modelMake: "Nissan",
    price: 90000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 2.5,
    published: true,
  },
  {
    title: "Nissan Altima 2.5 S",
    images: [
      "henry-ajquejay/zdny8ipafyptjowhruf4",
      "henry-ajquejay/amrzxfiu0a67gzjuek05",
      "henry-ajquejay/mnxzvqf8vyrzk4exfte2",
      "henry-ajquejay/ggp65jtoi1ocxwyb0jb0",
      "henry-ajquejay/uak1lqmihbhpjdkpbgy4",
    ],
    modelYear: 2018,
    modelMake: "Nissan",
    price: 85000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 2.5,
    published: true,
  },
  {
    title: "Nissan Versa Advance",
    images: [
      "henry-ajquejay/ticlgy3b3dzfjxnaz6we",
      "henry-ajquejay/ufc8muleowmamdcimuxj",
      "henry-ajquejay/q3jmbsjrrdaullocymxd",
      "henry-ajquejay/ycrynvjlg0p3nfiezwd3",
      "henry-ajquejay/spphiebivjkxdb0rvkoy",
    ],
    modelYear: 2021,
    modelMake: "Nissan",
    price: 33000, // Updated price
    condition: "USED",
    transmission: "MANUAL",
    mileage: 12000,
    engineType: "DIESEL",
    engineCapacity: 1.6,
    published: true,
  },
  {
    title: "Ford F150 XLT Cabina Sencilla",
    images: [
      "henry-ajquejay/jnue21p5orr6khnumzjb",
      "henry-ajquejay/d91z67naj3l5cpgerau8",
      "henry-ajquejay/szrou6335hxskxdcxhav",
      "henry-ajquejay/xwoic8gg9u2du08wksle",
      "henry-ajquejay/fwsyaw56vgmnifzsiqdg",
    ],
    modelYear: 2020,
    modelMake: "Ford",
    price: 120000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 3.5,
    location: "Guatemala City",
    published: true,
  },
  {
    title: "Volkswagen Nivus Highline",
    images: [
      "henry-ajquejay/fwsyaw56vgmnifzsiqdg",
      "henry-ajquejay/yopti3al8sndspthby3d",
      "henry-ajquejay/ayucn9zdhje3vs22typf",
      "henry-ajquejay/kvjsw9aaaggqcwjxsy2f",
      "henry-ajquejay/i6aklya6vbc89nvhtz5m",
    ],
    modelYear: 2022,
    modelMake: "Volkswagen",
    price: 42000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 15000,
    engineType: "PETROL",
    engineCapacity: 1.2,
    location: "Antigua",
    published: true,
  },
  {
    title: "Renault Kwid Intense",
    images: [
      "henry-ajquejay/kutoovgjggriazzqdch5",
      "henry-ajquejay/qitso131tudepq3x3b0q",
      "henry-ajquejay/adfhyxylwekgzs6qiuc3",
      "henry-ajquejay/yujw0kkph0jrq5hzhvvc",
      "henry-ajquejay/rfmpspcxpggpephmspa7",
    ],
    modelYear: 2024,
    modelMake: "Renault",
    price: 26000, // Updated price
    condition: "USED",
    transmission: "MANUAL",
    mileage: 5000,
    engineType: "PETROL",
    engineCapacity: 1.0,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Renault Stepway Intense",
    images: [
      "henry-ajquejay/gix7gqbn0x1xhabusefz",
      "henry-ajquejay/wtes3hffoijhiejymwl9",
      "henry-ajquejay/dfvgieizizwifjhoaesf",
      "henry-ajquejay/rishsex2klhq0mzddppt",
      "henry-ajquejay/jhktxsl8tt94uxxwxegi",
    ],
    modelYear: 2020,
    modelMake: "Renault",
    price: 32000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 30000,
    engineType: "PETROL",
    engineCapacity: 1.6,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "Kia Picanto X-Line 1.25 MT",
    images: [
      "henry-ajquejay/hphzfs1yqfolj16nh8hv",
      "henry-ajquejay/sjpcaqr3b6vnccdrc1jo",
      "henry-ajquejay/tejtex4go0tho1sgvc0n",
      "henry-ajquejay/frhldpfg04r35be1pgdz",
      "henry-ajquejay/rpgc1quu1nww3pbuqcvk",
    ],
    modelYear: 2023,
    modelMake: "Kia",
    price: 23000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.25,
    location: "Chimaltenango",
    published: true,
  },
  {
    title: "GMC Acadia SLE",
    images: [
      "henry-ajquejay/iy2db4lmf7hdrn5av0oj",
      "henry-ajquejay/nq2jmxm8uzxsimjlfvw2",
      "henry-ajquejay/vmq2wetqe7aenk1qni9b",
      "henry-ajquejay/slruclthqsxtqh7s2eab",
      "henry-ajquejay/o0wupeal3fpv9b5n9r4m",
      "henry-ajquejay/figcsmkr5m4lqokcfizj",
      "henry-ajquejay/x8ft177cjt1uafzpss6d",
    ],
    modelYear: 2019,
    modelMake: "GMC",
    price: 50000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 3.6,
    published: true,
  },
  {
    title: "Chevrolet Traverse LT Sport Utility 4D",
    images: [
      "henry-ajquejay/izzo4qb1o43bmri2amrz",
      "henry-ajquejay/z5sib4oud3zldkdypscb",
      "henry-ajquejay/ci5zs23izwqtpbpewxgp",
      "henry-ajquejay/qdb63xsb1mhzoftvt18c",
      "henry-ajquejay/ivfev2aghnga4rfxxami",
      "henry-ajquejay/epgirfemysloo1tbfi5v",
      "henry-ajquejay/ryqmrrz2kfm0drglqz3f",
      "henry-ajquejay/gi2lpmdv42n4cvwbpabp",
    ],
    modelYear: 2017,
    modelMake: "Chevrolet",
    price: 75000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 70000,
    engineType: "PETROL",
    engineCapacity: 3.6,
    published: true,
  },
  {
    title: "Chevrolet Trax LS Sport Utility 4D",
    images: [
      "henry-ajquejay/okiykp0v55d604nznz5x",
      "henry-ajquejay/d1czovnwzzbk8srm3pum",
      "henry-ajquejay/g465zg1caphpqwffs9ec",
      "henry-ajquejay/h8tghgjjdbfsjb4h4ojf",
      "henry-ajquejay/zgg4fycjnkvhbpwadhdo",
      "henry-ajquejay/jqxbmgnag2uhm5a4cdqe",
      "henry-ajquejay/gg34ivpuzidreg1cm2ym",
    ],
    modelYear: 2018,
    modelMake: "Chevrolet",
    price: 35000, // Updated price
    condition: "USED",
    transmission: "MANUAL",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 1.4,
    published: true,
  },
  {
    title: "Chevrolet Jeep Cherokee Trailhawk L Plus 4X4",
    images: [
      "henry-ajquejay/ziak91llffes3npkgsbt",
      "henry-ajquejay/edvqserpreuirgcpkkhf",
      "henry-ajquejay/eg7oqvfurqyxusiaypxn",
      "henry-ajquejay/yiuaq3cef9pqdy6yipd4",
      "henry-ajquejay/vcamiylghoxqcks04gib",
      "henry-ajquejay/dunlgcbmyvcozsofriop",
      "henry-ajquejay/l1jlbvr3rdf5mirrrec8",
      "henry-ajquejay/vq1wan8iow1ymm4kwq2a",
      "henry-ajquejay/u2sfoybvynz2hbjsgktx",
      "henry-ajquejay/yhtbytvjqbgfju40wyan",
    ],
    modelYear: 2019,
    modelMake: "Jeep",
    price: 58000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "DIESEL",
    engineCapacity: 2.0,
    published: true,
  },
  {
    title: "Nissan Altima 2.5 SV",
    images: [
      "henry-ajquejay/ytgzjbjkmviat2epwwlm",
      "henry-ajquejay/puhfwy4zqliujfnzowbx",
      "henry-ajquejay/qnw8ezdidx9r3pk88sau",
      "henry-ajquejay/wjibz4x5rv6gzxmsrcsg",
      "henry-ajquejay/p2negkxyxs1hotx3aujb",
      "henry-ajquejay/kw9eyr2jr5om0eczom9k",
    ],
    modelYear: 2018,
    modelMake: "Nissan",
    price: 37000, // Updated price
    condition: "USED",
    transmission: "AUTO",
    mileage: 55000,
    engineType: "PETROL",
    engineCapacity: 2.5,
    published: true,
  },
];

async function main() {
  console.log(`Deleting data...`);
  await prisma.car.deleteMany({});

  console.log(`Seeding database...`);

  for (const car of carData) {
    await prisma.car.create({
      data: car,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
  });
