import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const carData: Prisma.CarCreateInput[] = [
  {
    title: "Nissan Versa Advance",
    images: [
      "ticlgy3b3dzfjxnaz6we",
      "ufc8muleowmamdcimuxj",
      "q3jmbsjrrdaullocymxd",
      "ycrynvjlg0p3nfiezwd3",
      "spphiebivjkxdb0rvkoy",
    ],
    modelYear: 2020,
    modelMake: "Nissan",
    price: 55000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.6,
  },
  {
    title: "Ford F150 XLT Cabina Sencilla",
    images: [
      "jnue21p5orr6khnumzjb",
      "d91z67naj3l5cpgerau8",
      "szrou6335hxskxdcxhav",
      "xwoic8gg9u2du08wksle",
      "fwsyaw56vgmnifzsiqdg",
    ],
    modelYear: 2019,
    modelMake: "Ford",
    price: 250000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 3.5,
    location: "Chimaltenango",
  },
  {
    title: "Volkswagen Nivus Highline",
    images: [
      "fwsyaw56vgmnifzsiqdg",
      "yopti3al8sndspthby3d",
      "ayucn9zdhje3vs22typf",
      "kvjsw9aaaggqcwjxsy2f",
      "i6aklya6vbc89nvhtz5m",
    ],
    modelYear: 2021,
    modelMake: "Volkswagen",
    price: 300000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 20000,
    engineType: "DIESEL",
    engineCapacity: 1.0,
    location: "Chimaltenango",
  },
  {
    title: "Renault Kwid Intense",
    images: [
      "kutoovgjggriazzqdch5",
      "qitso131tudepq3x3b0q",
      "adfhyxylwekgzs6qiuc3",
      "yujw0kkph0jrq5hzhvvc",
      "rfmpspcxpggpephmspa7",
    ],
    modelYear: 2023,
    modelMake: "Renault",
    price: 200000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.0,
    location: "Chimaltenango",
  },
  {
    title: "Renault Stepway Intense",
    images: [
      "gix7gqbn0x1xhabusefz",
      "wtes3hffoijhiejymwl9",
      "dfvgieizizwifjhoaesf",
      "rishsex2klhq0mzddppt",
      "jhktxsl8tt94uxxwxegi",
    ],
    modelYear: 2020,
    modelMake: "Renault",
    price: 150000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 30000,
    engineType: "PETROL",
    engineCapacity: 1.6,
    location: "Chimaltenango",
  },
  {
    title: "Kia Picanto X-Line 1.25 MT",
    images: [
      "hphzfs1yqfolj16nh8hv",
      "sjpcaqr3b6vnccdrc1jo",
      "tejtex4go0tho1sgvc0n",
      "frhldpfg04r35be1pgdz",
      "rpgc1quu1nww3pbuqcvk",
    ],
    modelYear: 2023,
    modelMake: "Kia",
    price: 100000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 10000,
    engineType: "PETROL",
    engineCapacity: 1.25,
    location: "Chimaltenango",
  },
  {
    title: "GMC Acadia SLE",
    images: [
      "iy2db4lmf7hdrn5av0oj",
      "nq2jmxm8uzxsimjlfvw2",
      "vmq2wetqe7aenk1qni9b",
      "slruclthqsxtqh7s2eab",
      "o0wupeal3fpv9b5n9r4m",
      "figcsmkr5m4lqokcfizj",
      "x8ft177cjt1uafzpss6d",
    ],
    modelYear: 2019,
    modelMake: "GMC",
    price: 350000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 3.6,
  },
  {
    title: "Chevrolet Traverse LT Sport Utility 4D",
    images: [
      "izzo4qb1o43bmri2amrz",
      "z5sib4oud3zldkdypscb",
      "ci5zs23izwqtpbpewxgp",
      "qdb63xsb1mhzoftvt18c",
      "ivfev2aghnga4rfxxami",
      "epgirfemysloo1tbfi5v",
      "ryqmrrz2kfm0drglqz3f",
      "gi2lpmdv42n4cvwbpabp",
    ],
    modelYear: 2017,
    modelMake: "Chevrolet",
    price: 250000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 70000,
    engineType: "PETROL",
    engineCapacity: 3.6,
  },
  {
    title: "Chevrolet Trax LS Sport Utility 4D",
    images: [
      "okiykp0v55d604nznz5x",
      "d1czovnwzzbk8srm3pum",
      "g465zg1caphpqwffs9ec",
      "h8tghgjjdbfsjb4h4ojf",
      "zgg4fycjnkvhbpwadhdo",
      "jqxbmgnag2uhm5a4cdqe",
      "gg34ivpuzidreg1cm2ym",
    ],
    modelYear: 2018,
    modelMake: "Chevrolet",
    price: 200000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 1.4,
  },
  {
    title: "Chevrolet Jeep Cherokee Trailhawk L Plus 4X4",
    images: [
      "ziak91llffes3npkgsbt",
      "edvqserpreuirgcpkkhf",
      "eg7oqvfurqyxusiaypxn",
      "yiuaq3cef9pqdy6yipd4",
      "vcamiylghoxqcks04gib",
      "dunlgcbmyvcozsofriop",
      "l1jlbvr3rdf5mirrrec8",
      "vq1wan8iow1ymm4kwq2a",
      "u2sfoybvynz2hbjsgktx",
      "yhtbytvjqbgfju40wyan",
    ],
    modelYear: 2018,
    modelMake: "Jeep",
    price: 300000,
    condition: "USED",
    transmission: "MANUAL",
    mileage: 50000,
    engineType: "DIESEL",
    engineCapacity: 2.0,
  },
  {
    title: "Nissan Altima 2.5 SV",
    images: [
      "ytgzjbjkmviat2epwwlm",
      "puhfwy4zqliujfnzowbx",
      "qnw8ezdidx9r3pk88sau",
      "wjibz4x5rv6gzxmsrcsg",
      "p2negkxyxs1hotx3aujb",
      "kw9eyr2jr5om0eczom9k",
    ],
    modelYear: 2018,
    modelMake: "Nissan",
    price: 200000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 50000,
    engineType: "PETROL",
    engineCapacity: 2.5,
  },
  {
    title: "Nissan Altima 2.5 S",
    images: [
      "zdny8ipafyptjowhruf4",
      "amrzxfiu0a67gzjuek05",
      "mnxzvqf8vyrzk4exfte2",
      "ggp65jtoi1ocxwyb0jb0",
      "uak1lqmihbhpjdkpbgy4",
    ],
    modelYear: 2018,
    modelMake: "Nissan",
    price: 180000,
    condition: "USED",
    transmission: "AUTO",
    mileage: 60000,
    engineType: "PETROL",
    engineCapacity: 2.5,
  },
];

async function main() {
  console.log(`Deleting data...`);
  await prisma.car.deleteMany({});

  console.log(`Seeding database...`);

  for (const car of carData) {
    await prisma.car.create({
      data: car,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
  });
